# Generated by Django 5.1.1 on 2024-10-08 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='massage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
    ]
